//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public int Detail_ID { get; set; }
        public int Product_ID { get; set; }
        public string Order_ID { get; set; }
        public string Product_Name { get; set; }
        public int Quantity { get; set; }
        public decimal Total_Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
